version: '3.8'
services:
  aerospike:
    image: aerospike:ce-5.7.0.8
    platform: linux/amd64
    restart: always
    container_name: aerospike
    ports:
      - '3000-3002:3000-3002'
    volumes:
      - aerospike-data:/opt/aerospike/data
      - aerospike-config:/etc/aerospike
      - './aerospike.template.conf:/etc/aerospike/aerospike.template.conf'
volumes:
  aerospike-data:
  aerospike-config:
